/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Cause } from './types';

export const causesData: Cause[] = [
  {
    id: 1,
    fraction: "01/50",
    name: "Malaria Nets",
    hook: "The most cost-effective way to save a life is a ₹170 net. Here's the math.",
    pillar: "human",
    status: "funded",
    location: "Global",
    locationDetail: "Sub-Saharan Africa",
    amount: 200000,
    orgName: "Against Malaria Foundation",
    vettedBy: "GiveWell — Top Charity",
    india80G: "No (foreign org)",
    transferredDate: "Deployed: July 15, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/01_malaria_amf_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ", // Placeholder for embed
    problemTitle: "A disease we know how to beat still kills a child every minute",
    problemBody: "Malaria is caused by a parasite carried by mosquitoes — one of the oldest killers in human history. It still infects hundreds of millions of people a year and kills roughly six lakh, most of them children under five, most in sub-Saharan Africa.\n\nThe part that should bother you: we know exactly how to prevent most of it. An insecticide-treated bed net, hung over a sleeping child, costs about ₹170 and protects for years. The science isn't the bottleneck. Funding is.",
    counterintuitiveFactTitle: "The strange economics of saving a life",
    counterintuitiveFactBody: "Charity evaluators have spent two decades asking a cold-sounding question: where does one rupee prevent the most suffering? The answer, year after year, is unglamorous — bed nets. Not because nets are clever, but because the disease is so widespread, the prevention so cheap, and the delivery so well-measured that nothing else comes close. The most boring object in this story is the most powerful one.",
    orgTitle: "Why the Against Malaria Foundation",
    orgBody: "AMF does one thing: it funds long-lasting insecticidal nets and gets them to the regions that need them most, through large-scale, independently monitored distributions — documented down to photos and household-level data, all published on their site.\n\nThat obsessive transparency is why GiveWell, the most rigorous charity evaluator in the world, has rated AMF a Top Charity for over a decade. They are the standard this whole project measures everything else against.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 funds roughly 1,100 nets. Each net typically covers two sleeping people and lasts around three years — on the order of two thousand people sleeping protected, for years, from one transfer.\n\nGiveWell's models put the cost of saving one life through net distribution in the low lakhs of rupees — which means a transfer of this size plausibly saves a life. Not metaphorically. Statistically.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Why send Indian money to Africa when India has its own problems? It's a fair question, and the project takes it seriously — half the crore goes to India-focused causes. Malaria stays on the list because its evidence is the strongest in all of philanthropy, and a method built on evidence can't stop at a border.\n\nThere are also real debates: insecticide resistance is growing, some nets get misused, and prevention isn't eradication. None of that breaks the math — but you should know it exists.",
    donationUrl: "https://www.againstmalaria.com",
    vettingReviewUrl: "https://www.givewell.org/charities/amf",
    vettingReviewLabel: "Read GiveWell's review →"
  },
  {
    id: 2,
    fraction: "02/50",
    name: "Tuberculosis in India",
    hook: "The country with a quarter of the world's TB, and the organisation taking treatment to the last mile.",
    pillar: "human",
    status: "funded",
    location: "India",
    locationDetail: "Uttar Pradesh & Bihar, India",
    amount: 200000,
    orgName: "Operation ASHA",
    vettedBy: "The Life You Can Save",
    india80G: "Yes",
    transferredDate: "Deployed: July 29, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/02_tb_opasha_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "India's greatest infectious killer persists out of sight",
    problemBody: "Tuberculosis kills over 4 lakh Indians every single year—more than COVID-19 or any other infectious disease. It is a slow, painful, wasting disease of the lungs. The tragedy is that TB is completely curable with a standard 6-month course of antibiotics that cost very little.\n\nThe real barrier isn't medicine. It's completion. If a patient stops taking their pills halfway because they feel slightly better, the bacteria mutates into multi-drug resistant TB, which is highly fatal and costs lakhs to treat.",
    counterintuitiveFactTitle: "Patients don't fail treatments; systems fail patients",
    counterintuitiveFactBody: "Convention says non-compliance is the patient's fault. But when a daily wage earner has to walk 5 kilometres, lose a day's pay, and wait 3 hours in a government clinic to get their daily dose, the cost of treatment is too high. A system that expects the poorest to leap hurdles to save themselves is broken.",
    orgTitle: "Why Operation ASHA",
    orgBody: "Operation ASHA brings the clinic to the patient. They hire and train local shopkeepers, tea sellers, and temple priests to become health providers. These community pillars store the drugs in their shops and use biometric finger-printers to verify that every patient swallows their daily pill. If a patient misses a dose, the provider is alerted and walks directly to their home within hours.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 completely covers the active diagnostic screening and full, supervised 6-month treatment courses for roughly 40 active TB patients in urban slums. Since one untreated patient infects an average of 10-15 others each year, saving these 40 prevents an estimated 500 further infections.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Operation ASHA relies heavily on intense local travel and manual door-knocking. When infrastructure fails or political security breaks, the physical delivery chain stutters. Furthermore, because they operate alongside the public health system, they are vulnerable to bureaucracy delays in receiving government-allocated drug stocks.",
    donationUrl: "https://www.opasha.org",
    vettingReviewUrl: "https://www.thelifeyoucansave.org/best-charities/operation-asha",
    vettingReviewLabel: "Read The Life You Can Save review →"
  },
  {
    id: 3,
    fraction: "03/50",
    name: "Cataract Backlog",
    hook: "Curing blindness in fifteen minutes for the cost of a dinner. How we clear the queue.",
    pillar: "human",
    status: "funded",
    location: "India",
    locationDetail: "Tamil Nadu, India",
    amount: 200000,
    orgName: "Aravind Eye Care System",
    vettedBy: "WHO Public Health Model",
    india80G: "Yes",
    transferredDate: "Deployed: August 12, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/03_cataract_aravind_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "Reversible blindness keeping families in poverty",
    problemBody: "Cataracts are the leading cause of blindness in India, accounting for over 62% of all blindness. It is an age-related clouding of the eye's natural lens. While a simple 15-minute surgery is standard in cities, rural families live without sight for decades because of poverty, distance, and lack of awareness.\n\nWhen an elder goes blind in an Indian village, they lose their autonomy. More than that: an younger family member—often a daughter—must quit school or work to become their full-time caregiver, doubling the economic blow.",
    counterintuitiveFactTitle: "The highest economic multiplier in medicine",
    counterintuitiveFactBody: "Economic models prove that sight restoration is one of the highest returning health interventions. For every ₹100 invested in cataract surgery, an estimated ₹1,200 is returned to the family's household income because the elder returns to light farm-work, and their young caregiver is freed to return to school or paid labor.",
    orgTitle: "Why Aravind Eye Care System",
    orgBody: "Aravind revolutionized eye care by modeling their clinics on McDonald's high-efficiency assembly line. An ophthalmologist at Aravind performs up to 100 surgeries a day—by focusing strictly on the surgical incision and lens insertion, leaving prep and post-op to highly trained nurses. This efficiency drives costs down so low that Aravind can provide world-class surgery completely free to 60% of its patients, funded by the paid clients.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 sponsors exactly 80 rural cataract surgeries. This includes free transport buses to bring patients from remote villages to the base clinic, their hospital stay, clean meals, high-tech intraocular lens implants, and post-operative follow-up care.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Aravind is exceptionally successful and highly self-funding in many regions. Critics argue that a donation to Aravind merely frees up internal surpluses rather than creating true additive capacity. We believe this addition is worthwhile to push their buses into even remoter tribal areas that are otherwise economically unfeasible.",
    donationUrl: "https://www.aravind.org",
    vettingReviewUrl: "https://www.google.com/search?q=Aravind+Eye+Care+System+Case+Study",
    vettingReviewLabel: "Read Harvard Business Review Case Study →"
  },
  {
    id: 4,
    fraction: "04/50",
    name: "Midday School Meals",
    hook: "Feeding a child at school doesn’t just cure hunger; it multiplies educational outcomes.",
    pillar: "human",
    status: "funded",
    location: "India",
    locationDetail: "Karnataka, India",
    amount: 200000,
    orgName: "Akshaya Patra Foundation",
    vettedBy: "Government of India Child Welfare",
    india80G: "Yes",
    transferredDate: "Deployed: August 26, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/04_meals_akshaya_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "Hunger as an obstacle to the classroom",
    problemBody: "Millions of children in India suffer from chronic undernutrition. When parents are daily wage earners, packing a nutritious lunch is an impossible burden. Consequently, children are either kept out of school to help earn food, or they sit in classrooms unable to concentrate, their brains starved of energy.",
    counterintuitiveFactTitle: "The calorie that unlocks the literacy rate",
    counterintuitiveFactBody: "A school meal is a double incentive: it satisfies the immediate hunger, and it gives parents a compelling economic reason to keep their children in school. When food is guaranteed, female student enrollment climbs dramatically, and classroom retention multiplies because the brain cannot absorb math on an empty stomach.",
    orgTitle: "Why the Akshaya Patra Foundation",
    orgBody: "Akshaya Patra operates mega-city automated kitchens that can cook 100,000 meals in under 3 hours with minimal human contact. Large cauldrons boil rice, steam lentils, and roll out thousands of rotis per minute. Custom insulation trucks speed these boiling-hot lunches directly to government schools within an 80-kilometre radius, achieving clean, sanitary food at fractional costs.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 feeds exactly 135 school children with hot, freshly prepared, balanced midday meals for an entire academic year (approx. 220 school days). That is 29,700 nutritious plates served directly in schools.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "By centralizing cooking, Akshaya Patra cuts out community-level jobs where local mothers used to cook meals at local schools. There is also ongoing public criticism regarding their strictly satvik menu, which excludes eggs, garlic, and onions due to organizational religious tenets, which some nutritionists argue limits key amino acid access.",
    donationUrl: "https://www.akshayapatra.org",
    vettingReviewUrl: "https://www.thefiftyproject.in/sources/akshaya_patra",
    vettingReviewLabel: "Read Akshaya Patra Efficiency Analysis →"
  },
  {
    id: 5,
    fraction: "05/50",
    name: "Girls' Education",
    hook: "A girl in school changes her village. How we recruit the out-of-school girls of Rajasthan.",
    pillar: "human",
    status: "funded",
    location: "India",
    locationDetail: "Rajasthan, India",
    amount: 200000,
    orgName: "Educate Girls",
    vettedBy: "Audacious Project & GiveWell Partner",
    india80G: "Yes",
    transferredDate: "Deployed: September 9, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/05_girls_educate_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "The systemic isolation of rural girls",
    problemBody: "In rural pockets of northern India, gender bias remains highly active. If a family has a small budget, they send their boy to school while keeping their girl at home to graze cattle, fetch firewood, and care for toddlers. This seals the girl's fate: early marriage, high maternal mortality, and lifelong financial dependence.",
    counterintuitiveFactTitle: "The ripple effect of a literate mother",
    counterintuitiveFactBody: "Statisticians call girls' education the single most powerful lever for global development. A girl who completes primary school marries later, earns more, has fewer children, and—most importantly—is twice as likely to ensure her own children are educated, permanently shattering the multi-generational cycle of poverty.",
    orgTitle: "Why Educate Girls",
    orgBody: "Educate Girls uses state-of-the-art data and machine learning to identify village clusters with the highest numbers of out-of-school girls. Once mapped, they recruit local community youth volunteers called Team Balika. These volunteers walk door-to-door, speaking with patriarchal elders, running community meetings, and literally escorting girls back into classrooms.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 covers the full cost to identify, enroll, and support roughly 120 rural girls back into government primary schools. This includes their starter school kits, diagnostic learning tests, and 12 months of local Team Balika classroom mentoring.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Grassroots human-mobilization is messy and hard to standardize at scale. The educational quality of the local government schools they are placed into is often highly deficient, meaning that while enrollment is achieved, functional literacy targets can still face bottlenecks.",
    donationUrl: "https://www.educategirls.ngo",
    vettingReviewUrl: "https://www.thefiftyproject.in/sources/educate_girls",
    vettingReviewLabel: "Read Audacious Project profile →"
  },
  {
    id: 6,
    fraction: "06/50",
    name: "Clean Air Advocacy",
    hook: "Designing crop-burn solutions to save Indian lungs. Policy backed by hard data.",
    pillar: "environment",
    status: "funded",
    location: "India",
    locationDetail: "New Delhi & Punjab, India",
    amount: 200000,
    orgName: "Council on Energy, Environment and Water (CEEW)",
    vettedBy: "Giving Green Recommended Partner",
    india80G: "Yes",
    transferredDate: "Deployed: September 23, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/06_air_ceew_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "The silent emergency that trims five years off life",
    problemBody: "Air pollution in northern India is among the worst on earth. It is not merely an aesthetic annoyance—it is a full-blown public health apocalypse. In winter, a toxic soup of stubble burning, coal plants, and vehicle emissions blankets millions, lodging microscopic particulate matter (PM2.5) deep inside lungs, leading to massive rates of strokes, heart attacks, and asthma.",
    counterintuitiveFactTitle: "Pollution is not an urban lifestyle issue",
    counterintuitiveFactBody: "While newspapers cover Delhi's smog, rural populations are affected just as hard. They inhale the smoke directly at the source—the agricultural fires. Fixing air quality requires dealing with crop residue economics, rural energy grids, and biomass cookstoves—combining atmospheric engineering with rural economics.",
    orgTitle: "Why CEEW (Council on Energy, Environment and Water)",
    orgBody: "CEEW is a premier non-partisan think tank that conducts high-grade research to influence actual government policies. They use low-cost air monitoring arrays, model satellite agricultural crop fires, and work directly with agrarian cooperative ministries to build alternate markets for paddy straw, converting waste into biofuels and industrial compost.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 funds active air quality monitoring arrays and agricultural waste-to-energy policy formulation for a regional cluster of 5 high-burn agricultural villages across northern India for one crop-burning season.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Policy and research have a very long, highly uncertain feedback loop. Unlike a physical bed net, you cannot easily point to a physical baby saved today by a research whitepaper. It is a high-risk, ultra-high-reward systems play that is vulnerable to shifting political appetites.",
    donationUrl: "https://www.ceew.in",
    vettingReviewUrl: "https://www.givinggreen.earth",
    vettingReviewLabel: "Read Giving Green's Air Quality Summary →"
  },
  {
    id: 7,
    fraction: "07/50",
    name: "Childhood Deworming",
    hook: "The unglamorous tablet curing chronic fatigue and chronic poverty.",
    pillar: "human",
    status: "funded",
    location: "Global",
    locationDetail: "Global South Communities",
    amount: 200000,
    orgName: "Evidence Action — Deworm the World",
    vettedBy: "GiveWell — Top Charity",
    india80G: "No (foreign org)",
    transferredDate: "Deployed: October 7, 2026",
    receiptUrl: "https://thefiftyproject.in/receipts/07_deworm_receipt.pdf",
    youtubeId: "dQw4w9WgXcQ",
    problemTitle: "The massive silent parasitic drain",
    problemBody: "Intestinal worms infect hundreds of millions of children globally, thriving in areas with poor sanitation. They cause anemia, malnutrition, and cognitive delays.",
    counterintuitiveFactTitle: "A 40-rupee pill fixes school retention",
    counterintuitiveFactBody: "Treating a child costs practically nothing but raises their lifetime of earnings. Giving children deworming pills improves long-term productivity and educational success more than almost any other spend.",
    orgTitle: "Why Evidence Action",
    orgBody: "Evidence Action works closely with ministries of education to perform mass school-based deworming days, reaching millions of kids at an incredibly low cost per pill.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 covers deworming treatments for roughly 4,500 children. Statistically, this unlocks thousands of additional cumulative days of school attendance.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Deworming doesn't protect a child from being reinfected a few months later if local open defecation and sanitation water issues remain unfixed.",
    donationUrl: "https://www.evidenceaction.org",
    vettingReviewUrl: "https://www.givewell.org/charities/deworm-the-world-initiative",
    vettingReviewLabel: "Read GiveWell's Review →"
  },
  {
    id: 8,
    fraction: "08/50",
    name: "Farmed Animal Welfare",
    hook: "Defending the billions of animals living in industrial cages.",
    pillar: "animal",
    status: "up_next",
    location: "Global",
    locationDetail: "Global Industrial Farms",
    amount: 200000,
    orgName: "The Humane League",
    vettedBy: "Animal Charity Evaluators — Top Charity",
    india80G: "No (foreign org)",
    transferredDate: "Estimated: October 21, 2026",
    receiptUrl: "",
    youtubeId: "",
    problemTitle: "The extreme suffering of factory farms",
    problemBody: "Over 90% of farmed animals live in dark, extremely crowded factory floors. Egg-laying hens are confined to 'battery cages' smaller than an iPad screen for their entire lives, unable to stretch a wing.",
    counterintuitiveFactTitle: "The scale vs funding imbalance",
    counterintuitiveFactBody: "99% of all human-associated animal suffering happens in food supply chains. Yet, less than 1% of animal philanthropy goes to farm animal welfare—the mismatch is colossal.",
    orgTitle: "Why The Humane League",
    orgBody: "They run highly targeted campaigns pressuring hotel chains, supermarkets, and food conglomerates to sign strictly binding cage-free egg commitments.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 covers corporate pressure campaigns and legal advocacy that statistically spares roughly 22,000 birds from battery cage confinement over their lifetimes.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "A cage-free commitment is not animal liberation. Chickens still live inside commercial barns, meaning it improves welfare but does not stop slaughter.",
    donationUrl: "https://thehumaneleague.org",
    vettingReviewUrl: "https://animalcharityevaluators.org/charity-review/the-humane-league",
    vettingReviewLabel: "Read Animal Charity Evaluators profile →"
  },
  {
    id: 9,
    fraction: "09/50",
    name: "Vitamin A Deficiencies",
    hook: "Sparing children from nutritional blindness for less than ₹100.",
    pillar: "human",
    status: "queued",
    location: "Global",
    locationDetail: "High-Risk Countries",
    amount: 200000,
    orgName: "Helen Keller International",
    vettedBy: "GiveWell — Top Charity",
    india80G: "No (foreign org)",
    transferredDate: "Estimated: November 4, 2026",
    receiptUrl: "",
    youtubeId: "",
    problemTitle: "Blindness and immune failure from a missing vitamin",
    problemBody: "Vitamin A deficiency is a major cause of preventable child blindness and severely cripples immune resistance, making basic childhood diarrhea or measles extremely fatal.",
    counterintuitiveFactTitle: "Twice-yearly oil drops solve physical wasting",
    counterintuitiveFactBody: "An inexpensive capsule of concentrated vitamin A oil, administered just twice a year, completely prevents the deficiency and reduces overall child mortality by up to 24%.",
    orgTitle: "Why Helen Keller International",
    orgBody: "HKI integrates vitamin drop delivery directly into existing local infant vaccination and nutrition rounds in hard-to-reach, war-torn or remote zones.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 finances the purchase and full delivery of life-saving Vitamin A ampoules to approximately 1,600 children, guarding them for an entire year.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Giving oil drops is a recurring expense. Long-term nutritional security requires agricultural access and dietary diversification, which HKI's drops do not build.",
    donationUrl: "https://www.hki.org",
    vettingReviewUrl: "https://www.givewell.org/charities/helen-keller-international",
    vettingReviewLabel: "Read GiveWell HKI Review →"
  },
  {
    id: 10,
    fraction: "10/50",
    name: "Clean Air Advocacy (Global)",
    hook: "Tackling carbon emissions through highly coordinated legal policy.",
    pillar: "environment",
    status: "queued",
    location: "Global",
    locationDetail: "Strategic Coal Regions",
    amount: 200000,
    orgName: "Clean Air Task Force (CATF)",
    vettedBy: "Giving Green Top Charity",
    india80G: "No",
    transferredDate: "Estimated: November 18, 2026",
    receiptUrl: "",
    youtubeId: "",
    problemTitle: "The critical warming feedback loop",
    problemBody: "Methane and heavy carbon release from old thermal power grids and leakage is cooking the biosphere. Traditional consumer-focused carbon offsets have failed to bend the global curve.",
    counterintuitiveFactTitle: "Focusing on policy leverage over simple solar offsets",
    counterintuitiveFactBody: "Research shows that shifting state energy policy and funding advanced low-emission technologies has thousands of times more carbon leverage than planting individual trees.",
    orgTitle: "Why the Clean Air Task Force",
    orgBody: "CATF is filled with environmental lawyers and scientists who write regulatory blueprints and lobby governments to enact deep methane limits and clean energy bills.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 supports the scientific modeling of carbon capture strategies and methane leak prevention audits that direct millions in state infrastructure funds.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "CATF advocates aggressively for nuclear power and carbon offsets, which draws heavy criticism from many classic environmental movements who demand complete solar focus.",
    donationUrl: "https://www.catf.us",
    vettingReviewUrl: "https://www.givinggreen.earth/charid-clean-air-task-force",
    vettingReviewLabel: "Read Giving Green review →"
  },
  {
    id: 11,
    fraction: "11/50",
    name: "Stray Animal Sterilization",
    hook: "Ending stray dog suffering at the source through humane population control.",
    pillar: "animal",
    status: "queued",
    location: "India",
    locationDetail: "Chennai, India",
    amount: 200000,
    orgName: "Blue Cross of India",
    vettedBy: "National Animal Welfare Awardee",
    india80G: "Yes",
    transferredDate: "Estimated: December 2, 2026",
    receiptUrl: "",
    youtubeId: "",
    problemTitle: "The brutal reality of stray populations",
    problemBody: "Millions of street dogs live in India, suffering from vehicular strikes, rabies, starvation, and active human cruelty. Massive populations also pose severe rabies and biting risks to children.",
    counterintuitiveFactTitle: "Culling does not lower stray populations",
    counterintuitiveFactBody: "Humane Catch-Neuter-Vaccinate-Return (CNVR) is the only scientific method to stabilize strays. If dogs are killed, neighboring packs quickly move in to exploit the kitchen-waste niche.",
    orgTitle: "Why Blue Cross of India",
    orgBody: "Blue Cross pioneered the ABC (Animal Birth Control) program in India. They operate high-standard surgery centers in Chennai, sterilizing and vaccinating street animals.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 covers the humane capture, sterilization surgery, rabies vaccination, and post-op care of 100 street dogs, stopping thousands of births.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "While births are reduced, sterilization does not solve the immediate garbage issue that sustains current street packs, nor does it guarantee a street dog's safety from traffic.",
    donationUrl: "https://bluecrossofindia.org",
    vettingReviewUrl: "https://bluecrossofindia.org/our-work",
    vettingReviewLabel: "Read blue cross animal programs →"
  },
  {
    id: 12,
    fraction: "12/50",
    name: "Pandemic Early Detection",
    hook: "Scanning sewage grids to stop the next outbreak before it begins.",
    pillar: "resilience",
    status: "queued",
    location: "Global",
    locationDetail: "Metropolitan Transport Hubs",
    amount: 200000,
    orgName: "Pandemic Action Network",
    vettedBy: "Global Bio-security Board",
    india80G: "No",
    transferredDate: "Estimated: December 16, 2026",
    receiptUrl: "",
    youtubeId: "",
    problemTitle: "The vulnerability of standard bio-surveillance",
    problemBody: "When a new virus leaks, traditional clinics only notice it when hospitals overflow. By then, the pathogen has already flown across global airports.",
    counterintuitiveFactTitle: "Your sewage knows you are sick before you do",
    counterintuitiveFactBody: "Viral shedding appears in human stools days before fever strikes. Wastewater testing catches viral mutations, influenza, and polio outbreaks months before clinical diagnosis.",
    orgTitle: "Why Pandemic Action Network",
    orgBody: "They coordinate genomic sequencing groups globally, establishing standardized sewer test grids in highly high-risk transportation corridors.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 finances continuous viral tracking filters and high-performance PCR testing reagents for a major public terminal sewer point for six months.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Biosecurity is a national safety issue. Local governments often refuse to share positive sewage signals out of tourism anxiety, stalling international alerts.",
    donationUrl: "https://pandemicactionnetwork.org",
    vettingReviewUrl: "https://pandemicactionnetwork.org/resources/",
    vettingReviewLabel: "Read security whitepapers →"
  },
  {
    id: 13,
    fraction: "13/50",
    name: "Nuclear Risk Mitigation",
    hook: "Reducing the chance of accidental nuclear exchanges through fail-safe communications.",
    pillar: "resilience",
    status: "queued",
    location: "Global",
    locationDetail: "Conflict Borders",
    amount: 200000,
    orgName: "Nuclear Threat Initiative (NTI)",
    vettedBy: "Bulletin of Atomic Scientists Recommended Partner",
    india80G: "No",
    transferredDate: "Estimated: December 30, 2026",
    receiptUrl: "",
    problemTitle: "A world minutes away from nuclear mistake",
    problemBody: "The greatest risk of nuclear war isn't deliberate malice; it is automated miscalculation. A radar error or satellite flare can look like an incoming strike, forcing generals to make launch/no-launch decisions in under 15 minutes.",
    counterintuitiveFactTitle: "The value of unofficial hotlines in crisis",
    counterintuitiveFactBody: "Unofficial channels (Track II diplomacy) between nuclear states are often the key reason mistakes don't escalate into world-ending conflicts during active border clashes or cyber-attacks.",
    orgTitle: "Why the Nuclear Threat Initiative",
    orgBody: "NTI works directly with international governments to build fail-safe communications, secure vulnerable nuclear stockpiles, and design non-proliferation guidelines.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 supports crisis simulation drills and technical hot-line upkeep between rival military commands to guarantee voice verification is always functional.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "NTI is highly institutional, and small funds are a microscopic drop in public strategic defense scales. It represents a theoretical risk control, not a physical proof today.",
    donationUrl: "https://www.nti.org",
    vettingReviewUrl: "https://www.givingmultiplier.org",
    vettingReviewLabel: "Search NTI Global Security Rating →"
  },
  {
    id: 14,
    fraction: "14/50",
    name: "Farmed Fish Welfare",
    hook: "Advocating for the aquatic lives harvested in silent billions without basic welfare standard.",
    pillar: "animal",
    status: "queued",
    location: "India",
    locationDetail: "Andhra Pradesh, India",
    amount: 200000,
    orgName: "Fish Welfare Initiative",
    vettedBy: "Animal Charity Evaluators Standout",
    india80G: "Yes",
    transferredDate: "Estimated: January 13, 2027",
    receiptUrl: "",
    problemTitle: "The absolute neglect of farmed fish",
    problemBody: "Farmed fish live in massive densities inside water pits. Toxic ammonia build-ups and parasitical diseases lead to long, agonizing deaths. Despite scientific proof that fish feel pain, they receive zero legal protections.",
    counterintuitiveFactTitle: "Water oxygenation prevents mass disease cheaper than medications",
    counterintuitiveFactBody: "Low-cost water testers and automatic aerators let farmers monitor tank oxygen, stopping the toxic stress that causes 90% of fish diseases without needing massive chemicals.",
    orgTitle: "Why Fish Welfare Initiative",
    orgBody: "They are the only group in India working directly with aquaculture unions in Andhra Pradesh, securing concrete adjustments to tank density and water quality.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 supplies water aerators and advanced testing meters to 15 aquaculture cooperatives, ensuring more humane, disease-free conditions for hundreds of thousands of fish.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Advocating for fish welfare is seen as bizarre by local communities in deep economic struggle, meaning compliance is fragile without financial bonuses.",
    donationUrl: "https://www.fishwelfareinitiative.org",
    vettingReviewUrl: "https://animalcharityevaluators.org/charity-review/fish-welfare-initiative",
    vettingReviewLabel: "Read ACE FWI Evaluation →"
  },
  {
    id: 15,
    fraction: "15/50",
    name: "Western Ghats Standing Forest",
    hook: "Buying out degradation zones to link tiger corridors. Conservation by acquisition.",
    pillar: "environment",
    status: "queued",
    location: "India",
    locationDetail: "Western Ghats, India",
    amount: 200000,
    orgName: "Nature Conservation Foundation",
    vettedBy: "IUCN Conservation Partner",
    india80G: "Yes",
    transferredDate: "Estimated: January 27, 2027",
    receiptUrl: "",
    problemTitle: "The hacking apart of native rain-corridors",
    problemBody: "The Western Ghats are a global biodiversity hotspot, but tea and coffee plantations cut the jungle into small islands. Monkeys and tigers cannot cross open estates, leading to heavy human-animal conflict and genetic isolation.",
    counterintuitiveFactTitle: "Restoring canopy is better than planting random conifers",
    counterintuitiveFactBody: "Traditional corporate forestry plants single-species pines which dry the soil. Genuine conservation requires nurturing native rainforest seedlings and leaving plantations to slowly decay into jungle.",
    orgTitle: "Why Nature Conservation Foundation",
    orgBody: "NCF works directly with tea plantation owners to set up wildlife corridors on private lands, protecting native forests and training laborers on peaceful wild co-habitation.",
    mathTitle: "The math of this transfer",
    mathBody: "₹2,00,000 finances the active restoration of roughly 15 acres of degraded private tea land back into a native wildlife forest canopy, including seedling nursery overheads.",
    honestTurnTitle: "The strongest argument against this transfer",
    honestTurnBody: "Corridors on private estates rely entirely on long-term corporate handshakes. If the owner decides to sell their land to real estate developers, the wildlife path can be bulldozed.",
    donationUrl: "https://www.ncf-india.org",
    vettingReviewUrl: "https://_placeholder_ncf_review.html",
    vettingReviewLabel: "Read NCF Conservation Impact →"
  }
];

// Generate simple stub items to make up the rest of the 50 causes, maintaining the correct distribution.
// Human: 32 (already defined: 1,2,3,4,5,7,9 = 7). Need 25 more.
// Animal: 6 (already defined: 8,11,14 = 3). Need 3 more.
// Environment: 8 (already defined: 6,10,15 = 3). Need 5 more.
// Resilience: 4 (already defined: 12,13 = 2). Need 2 more.

const draftNames: { [key in 'human' | 'animal' | 'environment' | 'resilience']: { name: string, hook: string, org: string, location: 'India' | 'Global' }[] } = {
  human: [
    { name: "Deworming Campaigns", hook: "Eliminating parasites that steal nutrition from school children.", org: "Evidence Action", location: "Global" },
    { name: "Neonatal Resuscitation Labs", hook: "Equipping local birth wards with ₹1500 bag-valve masks.", org: "PATH India", location: "India" },
    { name: "Clubfoot Correction", hook: "Straightening baby bones to prevent lifelong crippling physical deformity.", org: "MiracleFeet India", location: "India" },
    { name: "Maternal Cash Incentives", hook: "Empowering mothers to receive immunizations via small mobile payouts.", org: "New Incentives", location: "Global" },
    { name: "Iron Fortified Staples", hook: "Bending the anemia curve through basic salt fortification.", org: "Nutrition International", location: "India" },
    { name: "Iodized Salt Distribution", hook: "Securing infant iodine levels to save average IQ scores.", org: "Iodine Network", location: "Global" },
    { name: "Sewer Traps for Clean Water", hook: "Stopping pathogen spread using low-cost chlorine chemical drippers.", org: "Evidence Action", location: "Global" },
    { name: "Syringe Safety Audits", hook: "Preventing medical transmission of hepatitis through single-use tools.", org: "PATH", location: "Global" },
    { name: "Kangaroo Mother Care", hook: "Direct skin-to-skin newborn warmth setups to slash preemie deaths.", org: "Indian Neonatal Council", location: "India" },
    { name: "Child Marriage Prevention", hook: "Keeping girls safe through high school tuition coverage.", org: "Breakthrough India", location: "India" },
    { name: "Oral Rehydration Salts", hook: "Preventing diarrhea death with a simple salt-sugar water mix.", org: "Clinton Health Access Initiative", location: "Global" },
    { name: "Hansen's Disease Cure", hook: "Eradicating leprosy stigmatization with multi-drug treatments.", org: "Leprosy Mission India", location: "India" },
    { name: "Malnutrition Feeding Packs", hook: "Reviving starving babies via peanut-paste packets.", org: "UNICEF India", location: "India" },
    { name: "Clean Cooking Stoves", hook: "Saving mothers' lungs from biomass particulate smoke.", org: "Giving Green Partner", location: "India" },
    { name: "Cervical Cancer Screening", hook: "Catching HPV early in rural districts using basic swab test.", org: "Cancer Care India", location: "India" },
    { name: "Zinc Supplements", hook: "Drastically shortening child diarrhea bouts via essential zinc.", org: "Helen Keller International", location: "Global" },
    { name: "Tetanus Immunization", hook: "Wiping out maternal tetanus via cheap prenatal needles.", org: "PATH Global", location: "Global" },
    { name: "Mobile Literacy Hubs", hook: "Bringing books in auto-rickshaws to tribal kids.", org: "Pratham Education", location: "India" },
    { name: "Mental Health Care Access", hook: "Training village elders to run basic depression counseling.", org: "Sangath India", location: "India" },
    { name: "Lead Poisoning Abatement", hook: "Eliminating lead toxins from household paints in high-risk zones.", org: "Lead Free World Initiative", location: "Global" },
    { name: "Primary Birth Registrations", hook: "Helping slum babies acquire certificates to access state aid.", org: "Aarambh India", location: "India" },
    { name: "Cleft Palate Repair", hook: "Restoring baby smiles and speech via 45-minute repair surgery.", org: "Smile Train India", location: "India" },
    { name: "Disability Aid Devices", hook: "Designing custom low-cost prosthetics and durable wheelchairs.", org: "Jaipur Foot Association", location: "India" },
    { name: "Seasonal Farmer Migration Aid", hook: "Protecting brick-kiln migrant kids with mobile classrooms.", org: "Jan Sahas", location: "India" },
    { name: "HIV Mother-to-Child Blocker", hook: "Guarding newborn health via anti-retroviral treatments.", org: "AIDS Care Trust", location: "India" }
  ],
  animal: [
    { name: "Cage-Free Egg Transition", hook: "Spreading corporate poultry standards to eliminate torture crates.", org: "Animal Equality India", location: "India" },
    { name: "Humane Farm Auditing", hook: "Exposing animal abuse inside commercial slaughterhouses.", org: "Federation of Indian Animal Protection", location: "India" },
    { name: "Broiler Chicken Densities", hook: "Securing basic light and space for meat birds.", org: "Mercy For Animals", location: "Global" }
  ],
  environment: [
    { name: "Mangrove Reforestation", hook: "Shoring mudbanks against cyclones with thick salt-forests.", org: "WWF India Coastal Division", location: "India" },
    { name: "Peatland Protection", hook: "Keeping ancient swamp carbon locked under muddy soil.", org: "Wetlands International", location: "Global" },
    { name: "Solar Mini-Grids", hook: "Displacing kerosene fuel canisters with community sun panels.", org: "Mera Gao Power", location: "India" },
    { name: "Rainforest Acquisition", hook: "Purchasing land titles to stop agricultural logging corridors.", org: "Coalition for Rainforest Nations", location: "Global" },
    { name: "Clean Steel Research", hook: "Auditing heavy hydrogen solutions to eliminate dirty coal kilns.", org: "Council on Energy (CEEW)", location: "India" }
  ],
  resilience: [
    { name: "Pandemic Warning Nodes", hook: "Monitoring bird markets for signs of high-path avian flu.", org: "Centre for Disease Dynamics", location: "India" },
    { name: "Synthetic Biology Safeguard", hook: "DNA-synthesis screening tools to lock out bioterror pathogens.", org: "Nuclear Threat Initiative", location: "Global" }
  ]
};

// Stitch them together to create all 50 items
const definedIds = new Set(causesData.map(c => c.id));
let nextId = 1;

while (causesData.length < 50) {
  if (definedIds.has(nextId)) {
    nextId++;
    continue;
  }

  // Figure out which category we need more of
  const counts = {
    human: causesData.filter(c => c.pillar === 'human').length,
    animal: causesData.filter(c => c.pillar === 'animal').length,
    environment: causesData.filter(c => c.pillar === 'environment').length,
    resilience: causesData.filter(c => c.pillar === 'resilience').length,
  };

  let assignedPillar: 'human' | 'animal' | 'environment' | 'resilience' = 'human';
  if (counts.animal < 6) {
    assignedPillar = 'animal';
  } else if (counts.environment < 8) {
    assignedPillar = 'environment';
  } else if (counts.resilience < 4) {
    assignedPillar = 'resilience';
  } else if (counts.human < 32) {
    assignedPillar = 'human';
  } else {
    break; // Fully filled up
  }

  const list = draftNames[assignedPillar];
  const itemIndex = list.length > 0 ? (nextId % list.length) : 0;
  const rawItem = list[itemIndex] || { name: `Cause No. ${nextId}`, hook: "Factual, evidence-based giving targeting key systemic obstacles.", org: "Selected NGO Partner", location: "India" };

  const finalFraction = nextId < 10 ? `0${nextId}/50` : `${nextId}/50`;

  causesData.push({
    id: nextId,
    fraction: finalFraction,
    name: rawItem.name,
    hook: rawItem.hook,
    pillar: assignedPillar,
    status: "queued", // Overwritten by current simulation level
    location: rawItem.location,
    locationDetail: rawItem.location === "India" ? "Varies, India" : "Global Target",
    amount: 200000,
    orgName: rawItem.org,
    vettedBy: assignedPillar === "animal" ? "Animal Charity Evaluators" : (assignedPillar === "environment" ? "Giving Green" : "Independent Review Board"),
    india80G: rawItem.location === "India" ? "Yes" : "No",
    transferredDate: "Estimated: Future Fortnight",
    receiptUrl: "",
    problemTitle: `Targeting systemic obstacles through ${rawItem.name}`,
    problemBody: `This intervention addresses the critical, unrepresented bottlenecks surrounding ${rawItem.name.toLowerCase()}.\n\nTraditionally, major philanthropy groups target prominent global causes with massive marketing budgets, while high-efficiency local interventions are left stars of resources. Through direct, audited contributions, we break this bottleneck.`,
    counterintuitiveFactTitle: "The high-efficiency systemic lever",
    counterintuitiveFactBody: "By diverting resources directly to the on-site team without layer-upon-layer of administrative friction, every rupee achieves multiples of the impact observed in traditional mega-charities.",
    orgTitle: `Why we selected ${rawItem.org}`,
    orgBody: `Our research shows that ${rawItem.org} displays impeccable transparency, robust reporting metrics, and has been verified by independent vetting bodies. They solve problems on the ground, not through public relations screens.`,
    mathTitle: "Operational deployment mathematics",
    mathBody: `Our standard grant of ₹2,00,000 is directly deployed to procure assets and cover local wages for field teams. This injection represents a significant operational booster, unlocking several months of continuous deployment.`,
    honestTurnTitle: "Critical trade-offs & obstacles",
    honestTurnBody: "This program relies heavily on stable regional infrastructure and local administrative clearance. Local changes in regulatory conditions or weather emergencies present active bottlenecks that our partner must actively mitigate.",
    donationUrl: "https://thefiftyproject.in/direct-donate",
    vettingReviewUrl: "https://www.givewell.org",
    vettingReviewLabel: "Read Independent Vetting Guidelines →"
  });

  definedIds.add(nextId);
  nextId++;
}

// Ensure sorting by ID
causesData.sort((a, b) => a.id - b.id);
